server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: local

  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # DB Setting
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test11
    username: root
    password: 1234
